# frozen_string_literal: true

source "https://rubygems.org"

gem 'webdrivers', '~> 4.0', require: false
gem 'cucumber', '5.2'
gem 'capybara', '3.33'
gem 'selenium-webdriver', '~> 4.3'
gem 'rspec', '3.10'
gem 'faker', '2.14'